# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import events_pb2 as events__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in events_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HLNodeAdapterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamPrices = channel.unary_stream(
                '/hl.events.HLNodeAdapter/StreamPrices',
                request_serializer=events__pb2.StreamRequest.SerializeToString,
                response_deserializer=events__pb2.MarketPriceEvent.FromString,
                _registered_method=True)
        self.StreamLiquidations = channel.unary_stream(
                '/hl.events.HLNodeAdapter/StreamLiquidations',
                request_serializer=events__pb2.StreamRequest.SerializeToString,
                response_deserializer=events__pb2.LiquidationEvent.FromString,
                _registered_method=True)
        self.StreamFills = channel.unary_stream(
                '/hl.events.HLNodeAdapter/StreamFills',
                request_serializer=events__pb2.StreamRequest.SerializeToString,
                response_deserializer=events__pb2.FillEvent.FromString,
                _registered_method=True)
        self.StreamStatus = channel.unary_stream(
                '/hl.events.HLNodeAdapter/StreamStatus',
                request_serializer=events__pb2.StreamRequest.SerializeToString,
                response_deserializer=events__pb2.SyncStatusEvent.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/hl.events.HLNodeAdapter/GetStatus',
                request_serializer=events__pb2.Empty.SerializeToString,
                response_deserializer=events__pb2.SyncStatusEvent.FromString,
                _registered_method=True)
        self.Handshake = channel.unary_unary(
                '/hl.events.HLNodeAdapter/Handshake',
                request_serializer=events__pb2.HandshakeRequest.SerializeToString,
                response_deserializer=events__pb2.HandshakeResponse.FromString,
                _registered_method=True)


class HLNodeAdapterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamPrices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLiquidations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFills(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Handshake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HLNodeAdapterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamPrices': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPrices,
                    request_deserializer=events__pb2.StreamRequest.FromString,
                    response_serializer=events__pb2.MarketPriceEvent.SerializeToString,
            ),
            'StreamLiquidations': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamLiquidations,
                    request_deserializer=events__pb2.StreamRequest.FromString,
                    response_serializer=events__pb2.LiquidationEvent.SerializeToString,
            ),
            'StreamFills': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFills,
                    request_deserializer=events__pb2.StreamRequest.FromString,
                    response_serializer=events__pb2.FillEvent.SerializeToString,
            ),
            'StreamStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamStatus,
                    request_deserializer=events__pb2.StreamRequest.FromString,
                    response_serializer=events__pb2.SyncStatusEvent.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=events__pb2.Empty.FromString,
                    response_serializer=events__pb2.SyncStatusEvent.SerializeToString,
            ),
            'Handshake': grpc.unary_unary_rpc_method_handler(
                    servicer.Handshake,
                    request_deserializer=events__pb2.HandshakeRequest.FromString,
                    response_serializer=events__pb2.HandshakeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hl.events.HLNodeAdapter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hl.events.HLNodeAdapter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HLNodeAdapter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamPrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hl.events.HLNodeAdapter/StreamPrices',
            events__pb2.StreamRequest.SerializeToString,
            events__pb2.MarketPriceEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLiquidations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hl.events.HLNodeAdapter/StreamLiquidations',
            events__pb2.StreamRequest.SerializeToString,
            events__pb2.LiquidationEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFills(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hl.events.HLNodeAdapter/StreamFills',
            events__pb2.StreamRequest.SerializeToString,
            events__pb2.FillEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hl.events.HLNodeAdapter/StreamStatus',
            events__pb2.StreamRequest.SerializeToString,
            events__pb2.SyncStatusEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hl.events.HLNodeAdapter/GetStatus',
            events__pb2.Empty.SerializeToString,
            events__pb2.SyncStatusEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Handshake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hl.events.HLNodeAdapter/Handshake',
            events__pb2.HandshakeRequest.SerializeToString,
            events__pb2.HandshakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
