# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import adapter_pb2 as adapter__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in adapter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HyperliquidNodeAdapterStub(object):
    """============ Service Definition ============

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamMarketPrices = channel.unary_stream(
                '/hyperliquid.adapter.HyperliquidNodeAdapter/StreamMarketPrices',
                request_serializer=adapter__pb2.StreamRequest.SerializeToString,
                response_deserializer=adapter__pb2.MarketPriceEvent.FromString,
                _registered_method=True)
        self.StreamActions = channel.unary_stream(
                '/hyperliquid.adapter.HyperliquidNodeAdapter/StreamActions',
                request_serializer=adapter__pb2.StreamRequest.SerializeToString,
                response_deserializer=adapter__pb2.ActionEvent.FromString,
                _registered_method=True)
        self.StreamPositions = channel.unary_stream(
                '/hyperliquid.adapter.HyperliquidNodeAdapter/StreamPositions',
                request_serializer=adapter__pb2.PositionStreamRequest.SerializeToString,
                response_deserializer=adapter__pb2.PositionStateEvent.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/hyperliquid.adapter.HyperliquidNodeAdapter/GetStatus',
                request_serializer=adapter__pb2.Empty.SerializeToString,
                response_deserializer=adapter__pb2.AdapterStatus.FromString,
                _registered_method=True)


class HyperliquidNodeAdapterServicer(object):
    """============ Service Definition ============

    """

    def StreamMarketPrices(self, request, context):
        """Stream market prices from SetGlobalAction events
        Returns continuous stream of MarketPriceEvent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamActions(self, request, context):
        """Stream all actions (orders, cancels, liquidations)
        Returns continuous stream of ActionEvent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPositions(self, request, context):
        """Stream position state changes from abci_state.rmp diffs
        Returns stream of PositionStateEvent when positions change
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get current adapter status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HyperliquidNodeAdapterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamMarketPrices': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMarketPrices,
                    request_deserializer=adapter__pb2.StreamRequest.FromString,
                    response_serializer=adapter__pb2.MarketPriceEvent.SerializeToString,
            ),
            'StreamActions': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamActions,
                    request_deserializer=adapter__pb2.StreamRequest.FromString,
                    response_serializer=adapter__pb2.ActionEvent.SerializeToString,
            ),
            'StreamPositions': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPositions,
                    request_deserializer=adapter__pb2.PositionStreamRequest.FromString,
                    response_serializer=adapter__pb2.PositionStateEvent.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=adapter__pb2.Empty.FromString,
                    response_serializer=adapter__pb2.AdapterStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hyperliquid.adapter.HyperliquidNodeAdapter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hyperliquid.adapter.HyperliquidNodeAdapter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HyperliquidNodeAdapter(object):
    """============ Service Definition ============

    """

    @staticmethod
    def StreamMarketPrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hyperliquid.adapter.HyperliquidNodeAdapter/StreamMarketPrices',
            adapter__pb2.StreamRequest.SerializeToString,
            adapter__pb2.MarketPriceEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamActions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hyperliquid.adapter.HyperliquidNodeAdapter/StreamActions',
            adapter__pb2.StreamRequest.SerializeToString,
            adapter__pb2.ActionEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hyperliquid.adapter.HyperliquidNodeAdapter/StreamPositions',
            adapter__pb2.PositionStreamRequest.SerializeToString,
            adapter__pb2.PositionStateEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperliquid.adapter.HyperliquidNodeAdapter/GetStatus',
            adapter__pb2.Empty.SerializeToString,
            adapter__pb2.AdapterStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
